### ISSUE TITLE
Deploy endorsers for all (most) ledgers

### ISSUE THREAD

**Issue by esune** [bcgov/dts-endorser-service#23]
Current endorser deployments only support CanDy dev/test/prod. 

We need to support other ledgers:
- [x] BCovrin dev/test/prod
  - Related ticket: https://github.com/bcgov/DITP-DevOps/issues/61
- [x] CANdy dev/test/prod
- [x] Sovrin StagingNet/MainNet
    - Related ticket; https://github.com/bcgov/DITP-DevOps/issues/28

Necessary for https://github.com/bcgov/traction/issues/408

**Comment by WadeBarnes** [comment]
Setup of endorsers for BCovrin legers is underway

**Comment by WadeBarnes** [comment]
Setup of endorsers for BCovrin legers is complete. Refer to https://github.com/bcgov/DITP-DevOps/issues/61 for details.

**Comment by WadeBarnes** [comment]
Setup of the endorsers for the Sovrin networks is underway.  Refer to https://github.com/bcgov/DITP-DevOps/issues/28 for details.

**Comment by WadeBarnes** [comment]
The portion of this task locking https://github.com/bcgov/traction/issues/408 has been completed; https://github.com/bcgov/DITP-DevOps/issues/61

**Comment by WadeBarnes** [comment]
This is complete.  Tasks have been created to track the related work of registering the issuer agents with the endorsers.
