### ISSUE TITLE
Create an Endorser Service based on ACA-Py

### ISSUE THREAD

**Issue by swcurran** [bcgov/dts-endorser-service#6]
Please create a basic Endorser Service using ACA-Py that can be deployed as needed and used to provide Hyperledger Indy network endorsing of transactions for authors to a given network.  The following is a brief summary of the requirements for the service, all of which are based on current functionality of ACA-Py.

- Be configured to have a public DID that is used for connections
  - Since we ultimately want to allow a single Endorser service to support multiple networks, the Endorser DID and public DID should be handled separately, even if they are the same DID. 
- Be configured to start up with a given endorser DID for a given network
  - The Service should know what network there Endorser is far, even if it Endorsers transactions only for a single network.
- An "allow" list of connections for which Endorsements are permitted.
- A mechanism to allow for extending the "allow" list of authors in a way that is as convenient as possible.
  - For example, accept the connection, receive an endorsement request, reject it, notify (somehow) somebody that a new author has a requested endorsing, update the allow list.
  - Ultimately, we want a UI for the service that allows for interactive handling of the allow list.
  - We need right away a method to know what authors are authorized to use the service. Perhaps an endpoint that lists the allow list along with the metadata about the authors.  That means that the administrators should include sufficient information on the allow list to be displayed -- e.g. name of service, URL for service, name of service contact, etc.
- Define a deployment approach for DTS that enables deploying two instances of the service (dev, test, prod each) supporting:
  - dev: BCovrin, CANdy-Dev
  - test:  Sovrin Staging, CANdy-Dev (later test)
  - prod: Sovrin MainNet, CANdy-Dev (later prod)
- Instructions for how to setup authors to use the service.

This could become a Hyperledger Aries repo.

**Comment by swcurran** [comment]
@ianco -- please take a look at this and come up with the best way to do this short term and long.  We need a short term version pretty quickly, but would like this to be a complete service in the long run -- e.g. handling endorsing transactions for multiple Indy networks, a user interface for administrators of the service, etc. However, we can take shortcuts initially -- e.g. restarting the service to add authors to the allow list.  But figuring out how to bootstrap an author in a reasonable smooth way is important.

One important use case right away is LSBC on Sovrin MainNet for revocations.  Somehow, we have to make sure that we can transition that instance from being an Endorser to being an Author without losing any revocations.

**Comment by ianco** [comment]
We have an endorser service in the traction repo (https://github.com/bcgov/traction/tree/develop/services/endorser)

Currently this is setup to auto-accept connections and auto-endorse any transaction requests, but could be modified per your requirements.  There is a controller implemented in python/FastAPI that currently doesn't do much other than make sure the connection meta-data is setup.

**Comment by ianco** [comment]
> One important use case right away is LSBC on Sovrin MainNet for revocations. Somehow, we have to make sure that we can transition that instance from being an Endorser to being an Author without losing any revocations.

Can you change a DID's role once it's written to the ledger?

**Comment by ianco** [comment]
I've created a hackmd here:  https://hackmd.io/@H1HgS-RdQMukDzKQtR7iNg/BJ_woLTH9

... and I've started populating the https://github.com/bcgov/aries-endorser-service repo

**Comment by WadeBarnes** [comment]
Done and deployed.  The initial set of issuers are rooted on CANdy, with a couple author services (IDIM and BC VC Pilot) connected.
